const express = require('express');
const { authMiddleware, roleCheck } = require('../middlewares/AuthMiddleware');
const BookingController = require('../controllers/BookingController');
const { BookingService }  = require('../services/BookingService');
const router = express.Router();
const service = new BookingService();
const controller = new BookingController(service);
router.use(authMiddleware);
router.post('/',   controller.createBooking);
router.get('/my',  controller.getMyBookings);
router.get('/pending',      roleCheck(['employee','admin']), controller.getPending);
router.post('/approve/:id', roleCheck(['employee','admin']), controller.approveBooking);
router.post('/reject/:id',  roleCheck(['employee','admin']), controller.rejectBooking);
router.post('/cancel/:id',  controller.cancelBooking);
router.get('/',             roleCheck(['employee','admin']), controller.getAll);
module.exports = router;
