const express = require('express');
const { roleCheck } = require('../middlewares/AuthMiddleware');
const { UserService } = require('../services/UserService');
const UserController = require('../controllers/UserController');
const router = express.Router();
const userService = new UserService();
const userController = new UserController(userService);
router.use(roleCheck(['admin']));
router.post('/', userController.create);
router.get('/',      userController.getAll);
router.get('/:id',   userController.getById);
router.put('/:id',   userController.update);
router.delete('/:id',userController.delete);
module.exports = router;
