const express        = require('express');
const ZoneController = require('../controllers/ZoneController');
const { ZoneService }= require('../services/ZoneService');
const { roleCheck }  = require('../middlewares/AuthMiddleware');
const router = express.Router();
const service    = new ZoneService();
const controller = new ZoneController(service);
router.get('/', controller.getAll);
router.use(roleCheck(['admin']));
router.post('/',   controller.create);
router.put('/:id', roleCheck(['admin']), controller.update);
router.delete('/:id', controller.delete);
module.exports = router;
